version: '3.8'

networks:
  web:
    driver: bridge

services:
  dev_db:
    networks:
        - web
    container_name: dev_db
    image: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postmoneeb
      - POSTGRES_PASSWORD=shammout123
      - POSTGRES_DB=tempDB
    volumes:
      - db_volume:/var/lib/postgresql/data

  # node_redis:
  #   container_name: node_redis
  #   image: redis:7.0-alpine
  #   ports:
  #     - '6379:6379'
  #   volumes:
  #     - db_volume:/var/lib/redis/data

volumes:
  db_volume: {}
  # redis_volume: {}