version: '3.8'
networks:
  stack-network:
    external:
      name: stack-network
  gateway-proxy-network:
    driver: bridge
  service-proxy-network:
    driver: bridge
  grpc-proxy-network:
    driver: bridge


services:
  api-gateway-1:
    extends:
      file: gateway/deployment/docker-compose.yaml
      service: api-gateway
    environment:
      - APP=First Gateway
    volumes:
      - ./gateway_config.json:/app/gateway_config.json
    networks:
      - gateway-proxy-network

  api-gateway-2:
    extends:
      file: gateway/deployment/docker-compose.yaml
      service: api-gateway
    environment:
      - APP=Second Gateway
    volumes:
      - ./gateway_config.json:/app/gateway_config.json
    networks:
      - gateway-proxy-network

  gateway-proxy:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx-proxy/gateway.conf:/etc/nginx/nginx.conf
    depends_on:
      - api-gateway-1
      - api-gateway-2
    networks:
      - gateway-proxy-network

  service-proxy:
    image: nginx
    ports:
      - 3000:80
    volumes:
      - ./nginx-proxy/service.conf:/etc/nginx/nginx.conf
    networks:
      - gateway-proxy-network
      - service-proxy-network

  user-service:
    extends:
      file: user-service/deployment/docker-compose.yaml
      service: user-service
    networks:
      - stack-network
      - service-proxy-network

  relay-service:
    extends:
      file: relay-service/deployment/docker-compose.yaml
      service: relay-service
    networks:
      - stack-network
      - service-proxy-network

  group-service:
    extends:
      file: group-service/deployment/docker-compose.yaml
      service: group-service
    networks:
      - stack-network
      - service-proxy-network

  discovery-service:
    extends:
      file: discovery-service/deployment/docker-compose.yaml
      service: discovery-service
    networks:
      - stack-network
      - service-proxy-network
      - grpc-proxy-network


  grpc-proxy:
    image: nginx
    ports:
      - 3001:80
    volumes:
      - ./nginx-proxy/grpc.conf:/etc/nginx/nginx.conf
    networks:
      - grpc-proxy-network

  websocket-manager-service:
    extends:
      file: websocket-manager/deployment/docker-compose.yaml
      service: websocket-manager-service
    networks:
      - stack-network
      - grpc-proxy-network

  message-service:
    extends:
      file: message-service/deployment/docker-compose.yaml
      service: message-service
    networks:
      - stack-network
      - grpc-proxy-network

  chat-service:
    extends:
      file: chat-service/deployment/docker-compose.yaml
      service: chat-service
    networks:
      - stack-network
      - grpc-proxy-network
      - service-proxy-network
    ports:
      - 9000:9000
      - 7000:7000

  last-seen-service:
    extends:
      file: last-seen-service/deployment/docker-compose.yaml
      service: last-seen-service
    networks:
      - stack-network
      - service-proxy-network