# version: '3.8'

# services:
#   websocket-manager-redis:
#     container_name: node_redis
#     image: redis:7.0-alpine
#     ports:
#       - '6379:6379'
#     volumes:
#       - redis_volume:/var/lib/redis/data

# volumes:
#   redis_volume: {}
