// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: protos/group-service.proto

package group_service_grpc_gen

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on GetGroupUsersRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetGroupUsersRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetGroupUsersRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetGroupUsersRequestMultiError, or nil if none found.
func (m *GetGroupUsersRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetGroupUsersRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for GroupId

	if len(errors) > 0 {
		return GetGroupUsersRequestMultiError(errors)
	}

	return nil
}

// GetGroupUsersRequestMultiError is an error wrapping multiple validation
// errors returned by GetGroupUsersRequest.ValidateAll() if the designated
// constraints aren't met.
type GetGroupUsersRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetGroupUsersRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetGroupUsersRequestMultiError) AllErrors() []error { return m }

// GetGroupUsersRequestValidationError is the validation error returned by
// GetGroupUsersRequest.Validate if the designated constraints aren't met.
type GetGroupUsersRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetGroupUsersRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetGroupUsersRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetGroupUsersRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetGroupUsersRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetGroupUsersRequestValidationError) ErrorName() string {
	return "GetGroupUsersRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetGroupUsersRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetGroupUsersRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetGroupUsersRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetGroupUsersRequestValidationError{}

// Validate checks the field values on GetGroupUsersResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetGroupUsersResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetGroupUsersResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetGroupUsersResponseMultiError, or nil if none found.
func (m *GetGroupUsersResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetGroupUsersResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Status

	if len(errors) > 0 {
		return GetGroupUsersResponseMultiError(errors)
	}

	return nil
}

// GetGroupUsersResponseMultiError is an error wrapping multiple validation
// errors returned by GetGroupUsersResponse.ValidateAll() if the designated
// constraints aren't met.
type GetGroupUsersResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetGroupUsersResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetGroupUsersResponseMultiError) AllErrors() []error { return m }

// GetGroupUsersResponseValidationError is the validation error returned by
// GetGroupUsersResponse.Validate if the designated constraints aren't met.
type GetGroupUsersResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetGroupUsersResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetGroupUsersResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetGroupUsersResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetGroupUsersResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetGroupUsersResponseValidationError) ErrorName() string {
	return "GetGroupUsersResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetGroupUsersResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetGroupUsersResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetGroupUsersResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetGroupUsersResponseValidationError{}
