// for validation examples
// https://github.com/bufbuild/protovalidate/tree/main/examples

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: protos/group-message-service.proto

package group_message_service_grpc_gen

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	GroupMessageService_Send_FullMethodName = "/GroupMessageService.GroupMessageService/Send"
)

// GroupMessageServiceClient is the client API for GroupMessageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GroupMessageServiceClient interface {
	Send(ctx context.Context, in *SendRequest, opts ...grpc.CallOption) (*SendResponse, error)
}

type groupMessageServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGroupMessageServiceClient(cc grpc.ClientConnInterface) GroupMessageServiceClient {
	return &groupMessageServiceClient{cc}
}

func (c *groupMessageServiceClient) Send(ctx context.Context, in *SendRequest, opts ...grpc.CallOption) (*SendResponse, error) {
	out := new(SendResponse)
	err := c.cc.Invoke(ctx, GroupMessageService_Send_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GroupMessageServiceServer is the server API for GroupMessageService service.
// All implementations must embed UnimplementedGroupMessageServiceServer
// for forward compatibility
type GroupMessageServiceServer interface {
	Send(context.Context, *SendRequest) (*SendResponse, error)
	mustEmbedUnimplementedGroupMessageServiceServer()
}

// UnimplementedGroupMessageServiceServer must be embedded to have forward compatible implementations.
type UnimplementedGroupMessageServiceServer struct {
}

func (UnimplementedGroupMessageServiceServer) Send(context.Context, *SendRequest) (*SendResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Send not implemented")
}
func (UnimplementedGroupMessageServiceServer) mustEmbedUnimplementedGroupMessageServiceServer() {}

// UnsafeGroupMessageServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GroupMessageServiceServer will
// result in compilation errors.
type UnsafeGroupMessageServiceServer interface {
	mustEmbedUnimplementedGroupMessageServiceServer()
}

func RegisterGroupMessageServiceServer(s grpc.ServiceRegistrar, srv GroupMessageServiceServer) {
	s.RegisterService(&GroupMessageService_ServiceDesc, srv)
}

func _GroupMessageService_Send_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GroupMessageServiceServer).Send(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GroupMessageService_Send_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GroupMessageServiceServer).Send(ctx, req.(*SendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GroupMessageService_ServiceDesc is the grpc.ServiceDesc for GroupMessageService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GroupMessageService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "GroupMessageService.GroupMessageService",
	HandlerType: (*GroupMessageServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Send",
			Handler:    _GroupMessageService_Send_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/group-message-service.proto",
}
