version: '3.8'

services:
  zookeeper1:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper1
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zookeeper1:2888:3888

  zookeeper2:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper2
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zookeeper1:2888:3888 server.2=zookeeper2:2888:3888