version: '3.8'

services:
  zookeeper1:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper1
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zookeeper1:2888:3888
      ZOO_SERVER_USERS: admin,user1
      ALLOW_ANONYMOUS_LOGIN: "yes"
      ZOO_ENABLE_AUTH: "no" 

    ports:
      - "2181:2181"
    restart: unless-stopped

  zookeeper2:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper2
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zookeeper1:2888:3888 server.2=zookeeper2:2888:3888
      ZOO_SERVER_USERS: admin,user1
      ALLOW_ANONYMOUS_LOGIN: "yes"
      ZOO_ENABLE_AUTH: "no" 
    ports:
      - "2182:2181"
    restart: unless-stopped

  zookeeper3:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper3
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zookeeper1:2888:3888 server.2=zookeeper2:2888:3888 server.3=zookeeper3:2888:3888
      ZOO_SERVER_USERS: admin,user1
      ALLOW_ANONYMOUS_LOGIN: "yes"
      ZOO_ENABLE_AUTH: "no" 
    ports:
      - "2183:2181"
    restart: unless-stopped

  zoonavigator-web:
    image: elkozmon/zoonavigator:latest
    container_name: zoonavigator-web
    depends_on:
      - zookeeper1
      - zookeeper2
      - zookeeper3
    ports:
      - "9000:9000"

    environment:
      CONNECTION_LOCALZK_CONN: zookeeper3:2181
    restart: unless-stopped