// Code generated by "gocqlx/cmd/schemagen"; DO NOT EDIT.

package models

import (
	"github.com/scylladb/gocqlx/v3/table"
	"time"
)

// Table models.
var (
	GocqlxMigrate = table.New(table.Metadata{
		Name: "gocqlx_migrate",
		Columns: []string{
			"checksum",
			"done",
			"end_time",
			"name",
			"start_time",
		},
		PartKey: []string{
			"name",
		},
		SortKey: []string{},
	})

	Messages = table.New(table.Metadata{
		Name: "messages",
		Columns: []string{
			"created_at",
			"id",
			"message",
			"receiver_id",
			"sender_id",
		},
		PartKey: []string{
			"id",
		},
		SortKey: []string{},
	})

	MessagesReceiverIdIdxIndex = table.New(table.Metadata{
		Name: "messages_receiver_id_idx_index",
		Columns: []string{
			"id",
			"idx_token",
			"receiver_id",
		},
		PartKey: []string{
			"receiver_id",
		},
		SortKey: []string{
			"idx_token",
			"id",
		},
	})

	Notifications = table.New(table.Metadata{
		Name: "notifications",
		Columns: []string{
			"created_at",
			"id",
			"message_id",
		},
		PartKey: []string{
			"id",
		},
		SortKey: []string{},
	})
)

type GocqlxMigrateStruct struct {
	Checksum  string
	Done      int32
	EndTime   time.Time
	Name      string
	StartTime time.Time
}
type MessagesStruct struct {
	CreatedAt  time.Time
	Id         [16]byte
	Message    string
	ReceiverId string
	SenderId   string
}
type MessagesReceiverIdIdxIndexStruct struct {
	Id         [16]byte
	IdxToken   int64
	ReceiverId string
}
type NotificationsStruct struct {
	CreatedAt time.Time
	Id        [16]byte
	MessageId [16]byte
}
