// Code generated by "gocqlx/cmd/schemagen"; DO NOT EDIT.

package models

import (
	"github.com/scylladb/gocqlx/v3/table"
	"time"
)

// Table models.
var (
	GocqlxMigrate = table.New(table.Metadata{
		Name: "gocqlx_migrate",
		Columns: []string{
			"checksum",
			"done",
			"end_time",
			"name",
			"start_time",
		},
		PartKey: []string{
			"name",
		},
		SortKey: []string{},
	})

	Messages = table.New(table.Metadata{
		Name: "messages",
		Columns: []string{
			"created_at",
			"id",
			"message",
			"receiverid",
			"senderid",
		},
		PartKey: []string{
			"id",
		},
		SortKey: []string{},
	})

	MessagesReceiveridIdxIndex = table.New(table.Metadata{
		Name: "messages_receiverid_idx_index",
		Columns: []string{
			"id",
			"idx_token",
			"receiverid",
		},
		PartKey: []string{
			"receiverid",
		},
		SortKey: []string{
			"idx_token",
			"id",
		},
	})

	Notifications = table.New(table.Metadata{
		Name: "notifications",
		Columns: []string{
			"created_at",
			"id",
			"messageid",
		},
		PartKey: []string{
			"id",
		},
		SortKey: []string{},
	})
)

type GocqlxMigrateStruct struct {
	Checksum  string
	Done      int32
	EndTime   time.Time
	Name      string
	StartTime time.Time
}
type MessagesStruct struct {
	CreatedAt  time.Time
	Id         int64
	Message    string
	Receiverid string
	Senderid   string
}
type MessagesReceiveridIdxIndexStruct struct {
	Id         int64
	IdxToken   int64
	Receiverid string
}
type NotificationsStruct struct {
	CreatedAt time.Time
	Id        int64
	Messageid int64
}
